version: "3.9"

services:
  postgres:
    build: ./src/db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "17017:5432"
    networks:
      - appnet

  app:
    build: .
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASS: pass
      DB_NAME: db
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
