version: "3.9"

services:
  postgres:
    build: ./src/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql

  app:
    build:
      context: .
      target: development
      # target: production
    command: ["npm", "run", "start:dev"]
    # command: ["npm", "run", "start:prod"]
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
      CRYPT_SALT: ${CRYPT_SALT}
      PORT: ${PORT}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${APP_PORT}:${PORT}"
    networks:
      - appnet
    restart: on-failure

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data:
  postgres_logs:
